import type { Metadata } from "next";
import { Inter, Kanit } from "next/font/google";
import "./globals.css";
import favicon from "./favicon.ico";
import Navbar from "../components/Navbar";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import Footer from "../components/Footer";
import theme from "./theme";

const inter = Inter({ subsets: ["latin"] });
const kanitFont = Kanit({
  subsets: ["latin"],
  weight: ["400", "700"],
  style: ["normal", "italic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "WE Space | Live a meaningful life |",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const faviconUrl = favicon.src;
  return (
    <html lang="en">
      <link rel="icon" href={faviconUrl} />
      <body className={kanitFont.className}>
        <ThemeProvider theme={theme}>
          <Navbar />
          <main>{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
